version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '<DB_NAME>'
      MYSQL_USER: '<USER>'
      MYSQL_PASSWORD: '<PASSWORD>'
      MYSQL_ROOT_PASSWORD: '<ROOT_PASSWORD>'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /mnt/app/mysql/:/var/lib/mysql
      - /mnt/mysql/conf.d/:/etc/mysql/conf.d
