version: '3'
services:
    mongo:
        container_name: mongo
        image: mongo:3
        restart: always
        volumes:
          - mongo_data:/data/db
        networks:
          - graylog
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
        restart: always
        environment: 
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
              soft: -1
              hard: -1
        volumes:
          - es_data:/usr/share/elasticsearch/data
        networks:
          - graylog
    graylog:
        container_name: graylog
        image: graylog/graylog:3.3
        restart: always
        environment: 
            - GRAYLOG_PASSWORD_SECRET=9002support@@graylog
            # Password: admin
            - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
        volumes:
          - graylog_data:/usr/share/graylog/data
        networks:
            - graylog
        depends_on:
          - mongo
          - elasticsearch
        ports:
          - 9000:9000
          - 12201:12201
          - 12201:12201/udp
          - 1514:1514
          - 1514:1514/udp

networks:
  graylog:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local