version: '3.1'
services:
  vault:
    image: vault:latest
    restart: always
    container_name: vault_master
    command: vault server -config /vault/config/local.json &
    ports:
      - 8200:8200
    volumes:
      - ./config:/vault/config
      - ./ssl:/vault/cert
    environment:
      - VAULT_CLUSTER_ADDR=https://mgchahad.vault.com
      - VAULT_API_ADDR=https://mgchahad.vault.com:8200
    cap_add:
    - IPC_LOCK
    depends_on:
    - "mysql"
  vault_2:
    image: vault:latest
    restart: always
    container_name: vault_slave
    command: vault server -config /vault/config/local.json &
    ports:
      - 8300:8200
    volumes:
      - ./config:/vault/config
      - ./ssl:/vault/cert
    environment:
      - VAULT_CLUSTER_ADDR=https://mgchahad.vault.com
      - VAULT_API_ADDR=https://mgchahad.vault.com:8200
    cap_add:
    - IPC_LOCK
    depends_on:
    - "mysql"
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '<DB_NAME>'
      MYSQL_USER: '<USER>'
      MYSQL_PASSWORD: '<PASSWORD>'
      MYSQL_ROOT_PASSWORD: '<ROOT_PASSWORD>'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
